### ISSUE TITLE
assetRootURL override not working

### ISSUE THREAD

**Issue by johno1985** [irundaia/sbt-sassify#20]
We have a slightly different directory structure in our project.
Our assets directory resides under /app/uk.myorg.com/assets.

In our Sbt build file we have set SassKeys.assetRootURL := "/uk.myorg.com". When we build, no css files are generated and nothing is output in the target directory.

**Comment by irundaia** [comment]
I believe you're misinterpreting the `assetsRootUrl` setting. This setting only affects the source maps. This is supposed to be the url where the source code will be *hosted*.

So suppose you've got a `main.scss` and you're hosting it at `your.host.org/foo/main.scss`. The `assetsRootUrl` setting will ensure that the browser can find the source when you're inspecting the original code.

What you're probably looking for, is a way to change the source directory. Since you're assets are in the `app/uk.myorg.com/assets`, you should include something the following in your build.sbt:

```scala
sourceDirectory in Assets := (sourceDirectory in Compile).value / "uk.myorg.com" / "assets"
```

Note that this assumes that `sourceDirectory in Compile` points to your `app` directory.
Does this help in solving your problem?

**Comment by johno1985** [comment]
Ahh! Yes, thanks Han

**Comment by irundaia** [comment]
That was fast! ^^ 

You're welcome
